# Generated by Django 3.2.6 on 2023-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimental', '0002_brands_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='Avg_Polarity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='brands',
            name='Avg_Subjectivity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
