# Generated by Django 3.2.6 on 2023-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimental', '0003_auto_20231114_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='Number_of_Reviews',
            field=models.IntegerField(default=0),
        ),
    ]
